### ISSUE TITLE
Merge TLC options prompt changes 

### ISSUE THREAD

**Issue by klinvill** [lemmy/vscode-tlaplus#7]
Opening this issue to continue the discussion from alygin/vscode-tlaplus#207.

Original comment:

> @klinvill Can you suggest how to logically merge your changes with the ones related to the TLC debugger? Both of us changed APIs in tla2tools.ts, but more fundamentally the TLC debugger integrates TLC with the VSCode launch API.

**Comment by klinvill** [comment]
My later changes to `runTlc()` replaced:
```javascript
const customOptions = getConfigOptions(CFG_TLC_OPTIONS);
```
with:
```javascript
const customOptions = await getTlcOptions(showOptionsPrompt);
if (customOptions === undefined) {
    // Command cancelled by user
    return undefined;
}
```

It looks like your changes to runTlc that conflict were mostly just adding [extra options](https://github.com/lemmy/vscode-tlaplus/commit/bf5d951fea8b6aa9bd721428e3c2977df4cb43a5#diff-e80d23f4b7cd3e6239725a763c1afa8e8967878007a176ad8b4b2d408bf674ecL95). As a result, the easiest change might be to do something like:
```javascript
const promptedOptions = await getTlcOptions(showOptionsPrompt);
if (promptedOptions === undefined) {
    // Command cancelled by user
    return undefined;
}
const customOptions = extraOpts.concat(promptedOptions);
```
I believe this should be compatible with both our changes and only require changing the name of the variable I use to store the prompted options.

Alternatively, it might be possible to consolidate extraOpts and the prompted options if the user could supply the extra options through the prompt. What are extraOpts used for?

**Comment by lemmy** [comment]
`extraOpts` is used to pass ```['-debugger', `port=${port}`]``` in https://github.com/lemmy/vscode-tlaplus/blob/bf5d951fea8b6aa9bd721428e3c2977df4cb43a5/src/debugger/debugging.ts#L71

Instead of `extraOpts`, I could obviously pre-populate the prompt with `-debugger port=34128`.  However, I fear that users accidentally remove or mess with the parameter when editing the prompt, and then wonder why the debugger fails.

**Comment by lemmy** [comment]
Btw. thanks for helping out with this!

**Comment by lemmy** [comment]
https://twitter.com/vanlightly/status/1395672906466746368 indicates that the debugger is actually useful for practitioners.  What's a path forward to have the debugger be merged into alygin/vscode-tlaplus (it seems you have commit rights)?

**Comment by klinvill** [comment]
Awesome, I'm glad to hear it! I haven't tried the debugger yet but it looks very helpful. 

Unfortunately it looks like the original repo has diverged quite a bit. I think the path forward is to rebase onto or merge with the latest master branch, and then open a PR in alygin/vscode-tlaplus.

In addition, I don't believe I have commit permissions for the project. My commits were just added through a PR that alygin merged. I'd be happy to help review a PR though (I should have permissions to do that)!

**Comment by lemmy** [comment]
https://github.com/alygin/vscode-tlaplus/pull/214

**Comment by lemmy** [comment]
Let's continue at https://github.com/alygin/vscode-tlaplus/pull/214
